### ISSUE TITLE
OpenStack-Ansible discovery driver

### ISSUE THREAD

**Issue by sc68cal** [Mirantis/Kostyor#86]
We currently have a `openstack` discovery driver, but I want to open a discussion about the `openstack-ansible` discovery driver.

The [`dynamic_inventory.py`](https://github.com/openstack/openstack-ansible/blob/master/playbooks/inventory/dynamic_inventory.py) script within openstack-ansible could be used, since it does return a [big `JSON`](https://github.com/sc68cal/Kostyor/blob/5f7589249a3f3b5a068e044bcb1fe151feca87f2/kostyor/tests/unit/upgrades/drivers/openstack_ansible_inventory.json) [blob](https://gist.github.com/sc68cal/72753f21c37c1d5e8de0a770ab77a487) that we could parse and create the required `Host`, `Service` and associated Kostyor db models. 

The question is, do we require an admin to `POST` the JSON blob to our API endpoint? That's probably the simplest way to go forward, but that requires an admin to pull the output of `dynamic_inventory.py` from their deployment node then push it into our API endpoint. That's a lot of manual work. Although would passing credentials for Kostyor to go into the deployment node via SSH and invoke it be better? I think there'd be a lot of operators that would balk at that, as well.

Thoughts? @kalnytskyi @jaypipes  @rk4n @jvarlamova @dstepanenko

**Comment by sc68cal** [comment]
This is related to #66

**Comment by kalnytskyi** [comment]
I don't think we should rely on explicit calling of `dynamic_inventory.py`. Playing around with it a bit I've discovered that it's called implicitly by Ansible internals according to `ansible.cfg` in OpenStack Mitaka, and `ANSIBLE_INVENTORY` env variable in OpenStack Newton. Besides I'd prefer to avoid hardcoding a part of that script.

To me it makes sense to use Celery task to do an actual discovering, the similar way to introspect inventory in OpenStack Ansible driver. The task, and the introspection code itself should be probably exposed via stevedore so we can have a separate `kostyor-openstack-ansible` repo with both `discovery` and `upgrade` drivers. Drawbacks of this approach is that an operator needs to properly run celery worker on the OpenStack Ansible Deployment Host.

What do you think guys?

**Comment by sc68cal** [comment]
Right, but I am asking - from the kostyor-cli - what are the required options that we need an operator to pass to Kostyor.

Do we have them upload the inventory file? Credentials to access the provisioning box?

**Comment by rk4n** [comment]
I'm somewhat out of context, so some things are not very obvious.
One way or another we need to rely on some interfaces exposed by OpenStack Ansible. 
By interfaces I mean not just API, but also scripts like in our case.
I think in our case user experience plays a key role.

@sc68cal 
> Although would passing credentials for Kostyor to go into the deployment node via SSH and invoke it be better?

Can we fetch this inventory using current user's ssh session, from kostyor-cli for example?

@ikalnytskyi 
> Besides I'd prefer to avoid hardcoding a part of that script.

You mean reimplementing discovery logic instead of using `dynamic_inventory.py` directly?

> To me it makes sense to use Celery task to do an actual discovering

Sorry for silly question, afaik discovery is smth like one-time task, not smth long-running. Why do we need to run celery?

**Comment by ikalnytskyi** [comment]
@sc68cal:
> Do we have them upload the inventory file? Credentials to access the provisioning box?

Not at all. :) I was talking about asking ops to run a celery worker on the host with all needed credentials loaded in env variables (`source /usr/local/bin/openstack-ansible.rc`). We will need anyway to run worker on the deployment host (provisioning box) in order to access openstack-ansible.

@rk4n:
> You mean reimplementing discovery logic instead of using dynamic_inventory.py directly?

I mean if we `source /usr/local/bin/openstack-ansible.rc`, and then create Ansible's `Inventory` instance, it will contain the proper inventory since it will trigger underlying inventory technique (dynamic inventory, in our case, since `openstack-ansible.rc` sets `ANSIBLE_INVENTORY`).

> Sorry for silly question, afaik discovery is smth like one-time task, not smth long-running. Why do we need to run celery?

Because we will need it anyway if we want Kostyor to orchestrate upgrades. Accessing deployment host via SSH, and then trying to fetch/do something there means:

* We need to solve credentials problem as @sc68cal mentioned above
* Rely on some third-party artifacts that are not guarantee to be there

So to me it seems like establishing pre-requirements to run a celery worker on the deployment host is most simple and secured approach so far.

**Comment by ikalnytskyi** [comment]
POC is available here:

https://github.com/Mirantis/kostyor-openstack-ansible/pull/1

**Comment by ikalnytskyi** [comment]
Close this as POC is merged to corresponding repo.
